const types = {

	// Movies

	FETCH_MOVIES_REQUEST: 'FETCH_MOVIES_REQUEST',
	FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
	FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_FAILURE',

	// Movie

	FETCH_SINGLE_MOVIE_REQUEST: 'FETCH_SINGLE_MOVIE_REQUEST',
	FETCH_SINGLE_MOVIE_SUCCESS: 'FETCH_SINGLE_MOVIE_SUCCESS',
	FETCH_SINGLE_MOVIE_FAILURE: 'FETCH_SINGLE_MOVIE_FAILURE',

	// Trailers

	FETCH_TRAILERS_REQUEST: 'FETCH_TRAILERS_REQUEST',
	FETCH_TRAILERS_SUCCESS: 'FETCH_TRAILERS_SUCCESS',
	FETCH_TRAILERS_FAILURE: 'FETCH_TRAILERS_FAILURE',

	// Images

	FETCH_IMAGES_REQUEST: 'FETCH_IMAGES_REQUEST',
	FETCH_IMAGES_SUCCESS: 'FETCH_IMAGES_SUCCESS',
	FETCH_IMAGES_FAILURE: 'FETCH_IMAGES_FAILURE',

	// Reviews

	FETCH_REVIEWS_REQUEST: 'FETCH_REVIEWS_REQUEST',
	FETCH_REVIEWS_SUCCESS: 'FETCH_REVIEWS_SUCCESS',
	FETCH_REVIEWS_FAILURE: 'FETCH_REVIEWS_FAILURE',

	// Cast

	FETCH_CAST_REQUEST: 'FETCH_CAST_REQUEST',
	FETCH_CAST_SUCCESS: 'FETCH_MOVIE_CAST_SUCCESS',
	FETCH_CAST_FAILURE: 'FETCH_CAST_FAILURE',

	// Similar movies

	FETCH_SIMILAR_MOVIES_REQUEST: 'FETCH_SIMILAR_MOVIES_REQUEST',
	FETCH_SIMILAR_MOVIES_SUCCESS: 'FETCH_SIMILAR_MOVIES_SUCCESS',
	FETCH_SIMILAR_MOVIES_FAILURE: 'FETCH_SIMILAR_MOVIES_FAILURE',

	// Genres

	FETCH_GENRES_REQUEST: 'FETCH_GENRES_REQUEST',
	FETCH_GENRES_SUCCESS: 'FETCH_GENRES_SUCCESS',
	FETCH_GENRES_FAILURE: 'FETCH_GENRES_FAILURE',

	// Person

	FETCH_PERSON_DETAILS_REQUEST: 'FETCH_PERSON_DETAILS_REQUEST',
	FETCH_PERSON_DETAILS_SUCCESS: 'FETCH_PERSON_DETAILS_SUCCESS',
	FETCH_PERSON_DETAILS_FAILURE: 'FETCH_PERSON_DETAILS_FAILURE',

	FETCH_PERSON_CREDITS_REQUEST: 'FETCH_PERSON_CREDITS_REQUEST',
	FETCH_PERSON_CREDITS_SUCCESS: 'FETCH_PERSON_CREDITS_SUCCESS',
	FETCH_PERSON_CREDITS_FAILURE: 'FETCH_PERSON_CREDITS_FAILURE',

	// User

	USER_SESSION_STARTED: 'USER_SESSION_STARTED',
	USER_AUTH_ERROR: 'AUTH_ERROR',
	USER_AUTH_ERROR_RESET: 'USER_AUTH_ERROR_RESET',
	USER_SESSION_REMOVED: 'USER_SESSION_REMOVED',

	// Watchlist

	FETCH_IDLIST_SUCCESS: 'FETCH_IDLIST_SUCCESS',

	FETCH_WATCHLIST_REQUEST: 'FETCH_WATCHLIST_REQUEST',
	FETCH_WATCHLIST_SUCCESS: 'FETCH_WATCHLIST_SUCCESS',
	FETCH_WATCHLIST_FAILURE: 'FETCH_WATCHLIST_FAILURE',

	MOVIE_ADDED_TO_WATCHLIST: 'MOVIE_ADDED_TO_WATCHLIST',
	MOVIE_REMOVED_FROM_WATCHLIST: 'MOVIE_REMOVED_FROM_WATCHLIST',
	WATCHLIST_CLEANED: 'WATCHLIST_CLEANED',

	FETCH_USER_REQUEST_STARTED: 'FETCH_USER_REQUEST_STARTED',
	USER_REQUEST_STATUS_RESET: 'USER_REQUEST_STATUS_RESET',
	FETCH_USER_REQUEST_FAILURE: 'FETCH_USER_REQUEST_FAILURE',

	// Menu

	MENU_OPENED: 'MENU_OPENED',
	MENU_CLOSED: 'MENU_CLOSED'

};

export default types;